### ISSUE TITLE
Differentiate between devdependencies and dependencies

### ISSUE THREAD

**Issue by MarkReeder** [nodesource/unpublished-dependencies#1]
It would be nice to differentiate between devdependencies and dependencies in the output as unpublished devdependencies won't impact projects relying on modules but unpublished dependencies will.

**Comment by julianduque** [comment]
Thats a great suggestion, thanks!

**Comment by julianduque** [comment]
Landed in https://github.com/nodesource/unpublished-dependencies/commit/30b499b035393b049cfaab5d83ffa599eb3d89c5 (v1.0.1)
